name: Update Search Index

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: yarn install

    - name: Generate Search Index
      run: yarn gen-search-index

    - name: Commit and Push Search Index Updates
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "Update search index" || echo "No changes to commit"
        git push origin "${GITHUB_REF#refs/heads/}" # Dynamically push to the current branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
